### ISSUE TITLE
Use php-saml >= 2.10.0

### ISSUE THREAD

**Issue by pitbulk** [asasmoyo/yii2-saml#1]
[php-saml 2.10.0](https://github.com/onelogin/php-saml/releases/tag/v2.10.0) version.
It includes a security patch that contains extra validations that will prevent signature wrapping attacks and other security improvements.Previous versions are vulnerable.

**Comment by asasmoyo** [comment]
oh thanks for reminding me! i have update composer.lock here
https://github.com/asasmoyo/yii2-saml/commit/e3275ef3a57e5a260632458d165192e8e7c52f35
