### ISSUE TITLE
saml google

### ISSUE THREAD

**Issue by jotnet** [asasmoyo/yii2-saml#13]
Hi,

`public function callback( $attributes ) {
		var_dump( base64_decode( $_REQUEST['SAMLResponse'] ) );
		echo '<br /><br />';
		print_r( $attributes );
		exit();}`
In $_REQUEST variable I have correct XML but $attributes is empty. Is this correct? $attributes doesnt return id or email.

**Comment by asasmoyo** [comment]
Are you sure `$_REQUEST['SAMLResponse']` holds the correct value? And I am pretty sure you don't need to do `base64_decode` to read `$_REQUEST['SAMLResponse']`. Any specific reason why are you doing this?

**Comment by asasmoyo** [comment]
closing for no response. feel free to open this again if you have another question
