### ISSUE TITLE
PHP 7.2 support

### ISSUE THREAD

**Issue by juliardi** [asasmoyo/yii2-saml#14]
According to https://github.com/onelogin/php-saml/issues/291, php-saml 2.x is not compatible with PHP 7.2. So I think we have to release a new major version for yii2-saml with php-saml 3.x  to be compatible with PHP 7.2. What do you think @asasmoyo ?

**Comment by asasmoyo** [comment]
It doesn't need to do major release, minor release should be ok. Is there any breaking php-saml api changes from 2.x to 3.x?

**Comment by juliardi** [comment]
Alright, php-saml 3.x release notes doesn't mention any api breaking changes from 2.x but I'll check it to be safe.

**Comment by asasmoyo** [comment]
@admr i just released version 1.7.0 with php-saml 3.x support. Please check if it works on your side

**Comment by admroz** [comment]
After quick tests it works for me. Thank you!
