### ISSUE TITLE
Support for php 7.2

### ISSUE THREAD

**Issue by admroz** [asasmoyo/yii2-saml#15]
We are preparing for php 7.2 upgrade, in order to do this we need yii2-saml ^1.5. But it depends on onlogin/php-saml ~2.13.0 which requires ext-mcrypt and this extension is removed in php 7.2.

```
> composer prohibits asasmoyo/yii2-saml 1.6
asasmoyo/yii2-saml  1.6.0       requires          onelogin/php-saml (~2.13.0)
my/project        dev-master  does not require  onelogin/php-saml (but v3.0.0 is installed)
```

If I'm trying to forece yii2-saml ^1.6 then I'm getting this:
```
- onelogin/php-saml v2.13.0 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
- asasmoyo/yii2-saml 1.6.0 requires onelogin/php-saml ~2.13.0 -> satisfiable by onelogin/php-saml[v2.13.0].
- Installation request for asasmoyo/yii2-saml ^1.6 -> satisfiable by asasmoyo/yii2-saml[1.6.0].
```

There is onelogin/php-saml 3.0 available which removes mcrypt, could you please update your dependencies?

**Comment by asasmoyo** [comment]
Thanks for the report. We'll track this issue here https://github.com/asasmoyo/yii2-saml/issues/14
