### ISSUE TITLE
Multiple Idp's

### ISSUE THREAD

**Issue by jcrawford** [asasmoyo/yii2-saml#17]
Can this library handle multiple idp's?  I ask because we are currently integrated to an SSO with this package however we need to add another IDP for another client, however, from what I see in the readme it does not show how to setup the config to work with multiple idp's.  Is this possible with this package and if so can you show a quick example configuration?

**Comment by asasmoyo** [comment]
How do you decide which idp to use? I think as long as the 'switch' is accessible from config file, it should be possible

**Comment by jcrawford** [comment]
@asasmoyo currently we determine to use the IDP or not based on the domain in the users email address.  I do not see a way in the config file to outline multiple IDP's though and that is where I am having the issue.  If I could see a clear way to add multiple IDP's to the configuration file I would be able to determine which IDP to use based on the users email domain like they currently are for determining whether or not to use SSO at all.

This is all done in the LoginModel however, it's not in our config.  In our config we determine which IDP listed to use based on environment and in the config file I am not sure how I would say use this IDP for this user based on what criteria.  Currently we are only determining what the IDP is in the config based on environment (prod, qa, dev).  I am just getting familiar with SSO so I am not sure how I would list multiple IDP's in the configuration and determine which to use at this point.

The config only has a single idp array key, can i provide an array of idp's here and it still work with the library or will I have to do some magic trickery to make this work?

**Comment by asasmoyo** [comment]
I don't think adding support for multiple idps really worth the trouble as it is pretty rare use case (but feel free if you want to submit a pr for this :))

> currently we determine to use the IDP or not based on the domain in the users email address

I think you can create custom login action and decide which idp to use there. Take [this](https://github.com/asasmoyo/yii2-saml/blob/master/src/actions/LoginAction.php) for reference. 

`samlInstance` property in that class holds the idp configuration. You can do something like:

```
// modify config
if ($use_idp1) {
    $this->samlInstance->config['idp'] = $config_idp1;
} else if ($use_idp2) {
    $this->samlInstance->config['idp'] = $config_idp2;
}

// then do login
$this->samlInstance->login();
```

**Comment by asasmoyo** [comment]
I don't think adding support for multiple idps really worth the trouble as it is pretty rare use case (but feel free if you want to submit a pr for this :))

> currently we determine to use the IDP or not based on the domain in the users email address

I think you can create custom login action and decide which idp to use there. Take [this](https://github.com/asasmoyo/yii2-saml/blob/master/src/actions/LoginAction.php) for reference. 

`samlInstance` property in that class holds the idp configuration. You can do something like:

```
// modify config
if ($use_idp1) {
    $this->samlInstance->config['idp'] = $config_idp1;
} else if ($use_idp2) {
    $this->samlInstance->config['idp'] = $config_idp2;
}

// then do login
$this->samlInstance->login();
```

**Comment by jcrawford** [comment]
@asasmoyo thank you for that information I will take a look at what it will take to integrate this.  Yea it is a pretty rare use case, we just happen to have multiple clients which have SSO and want it integrated with our service.  Thank Again!
