### ISSUE TITLE
Possible error in the way you load the settings

### ISSUE THREAD

**Issue by pitbulk** [asasmoyo/yii2-saml#2]
I saw on your code the way you [load the setting file](https://github.com/asasmoyo/yii2-saml/blob/master/src/Saml.php#L37)

require method works similar to the include and if you check the example5 of the [include doc](http://php.net/manual/en/function.include.php) you will notice that the @app/config/saml.php must include a return of the setting var in order to be loaded, if not instead you are loading a true value (returned by require when the inclusion was ok)

In your documentation you reference to the php-saml settings that has no return so the users of your extension are not adding that return so they are experiemcing errors reported to my php-saml toolkit.

https://github.com/onelogin/php-saml/issues/38#issuecomment-75712010

The way to solve that:
- Add a warning on the docs and make ppl know that the setting file must contain a return.
- Instead of $xxx = require,  just call to require and assume that the $setting var is loaded after the call (you could check if that var was loaded and if not print a warning).

**Comment by asasmoyo** [comment]
whoops my bad. thanks for pointing my mistake! 
i'm working on it

**Comment by asasmoyo** [comment]
updated on https://github.com/asasmoyo/yii2-saml/releases/tag/1.3.0
