### ISSUE TITLE
Removing/modifying AuthnContext

### ISSUE THREAD

**Issue by amcoho** [asasmoyo/yii2-saml#24]
SAML auth request from SP to IdP issued by your extension by default includes the following section which we need to changed or drop completely since IdP we are trying to integrate with creates SSO session based on IWA (Integrated Windows Authentication), but SAML request from SP is asking for password login specifically. How do we achieve this with your extension?

<saml:AuthnContext>
  <saml:AuthnContextClassRef>
    urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport
  </saml:AuthnContextClassRef>
</saml:AuthnContext>

**Comment by asasmoyo** [comment]
this extension simply wraps https://github.com/onelogin/php-saml that handles SAML protocol. if you want to do custom SAML you should check php-saml
