### ISSUE TITLE
set retrieveParametersFromServer in call to processSLO

### ISSUE THREAD

**Issue by mehrdadziaei** [asasmoyo/yii2-saml#25]
For compatibility with AzureAD/ADFS we need to set retrieveParametersFromServer to true in the call to processSLO, but currently yii2-saml doesn't support passing any parameters to Auth->processSLO in php-saml.

Will this be updated so we can set retrieveParametersFromServer to true?

Thanks,

**Comment by asasmoyo** [comment]
I'll see what I can do. I'm thinking to allow call of functions to underlying php-saml instance via yii2-saml components somehow

**Comment by asasmoyo** [comment]
Would https://github.com/asasmoyo/yii2-saml/pull/27/files work? You can create your own `SlsAction` with `$retrieveParametersFromServer = true` when calling `processSLO` function

**Comment by mehrdadziaei** [comment]
Your change to saml.php would work just fine.
Then we will create our custom SlsAction.

Thanks,

**Comment by asasmoyo** [comment]
Perfect! I'll merge it and create a new release
