### ISSUE TITLE
onelogin advanced settings

### ISSUE THREAD

**Issue by harwoodr** [asasmoyo/yii2-saml#30]
Is there any easy way of setting advanced settings, such as authnRequestsSigned?

**Comment by asasmoyo** [comment]
you should be able to put it in your configuration file 

```
'components' => [
    'saml' => [
        'class' => 'asasmoyo\yii2saml\Saml',
        'configFileName' => '@app/config/saml.php', // the config file
    ]
]
```

example content is https://github.com/asasmoyo/yii2-saml/blob/master/tests/config/saml.php
