### ISSUE TITLE
How to access logged user details in successCallback?

### ISSUE THREAD

**Issue by wilkolazki** [asasmoyo/yii2-saml#32]
Hi,

I have set up saml authentication with your library and it seems to work, but I have no idea how to access the `nameid-format:emailAddress` returned by IDP.

The response I get from the IDP contains the email of the user, but does not contain any attributes, so the $attributes argument to the callback function is empty. 

The `_nameId` property of Auth class is filled correctly, but how can I access it?

**Comment by wilkolazki** [comment]
Demos of php-saml project suggest, that the main identity of a user is the `nameid` field, it is not possible to access it without modifying your code.

Please take a look at demo2 from onelogin/php-saml [consume.php](https://github.com/onelogin/php-saml/blob/master/demo2/consume.php):
```
if ($samlResponse->isValid()) {
            echo 'You are: ' . $samlResponse->getNameId() . '<br>';
            $attributes = $samlResponse->getAttributes();
            if (!empty($attributes)) {...}
```

The first thing you check is the `getNameId()` method. Only then optional attributes are enumerated.

I suggest adding the `nameid` as a second parameter to the callback on successful login.

**Comment by asasmoyo** [comment]
Hey, sorry for the delay. I think it's a good idea. I'll add `getNameId()` to login callback
