### ISSUE TITLE
The response was received at http://<appname>.azurewebsites.net/saml/acs instead of https://<appname>.azurewebsites.net/saml/acs

### ISSUE THREAD

**Issue by seshendramln** [asasmoyo/yii2-saml#43]
I have a PHP Yii2 application set up at Azure Web App Service Linux at URL https://<appname>.azurewebsites.net/saml/acs

I am using Azure  SAML SSO, configured according to the docs, I am getting an invalid response after successful MFA authentication step. 
When I debug I go the following error
The response was received at http://<appname>.azurewebsites.net/saml/acs instead of https://<appname>.azurewebsites.net/saml/acs

Please help me to solve the issue, it is stopping the business.

**Comment by motzy** [comment]
I have run into the same issue, this is possibly because your Yii2 app is behind a proxy or load balancer.

If this is the case, in your controller declare: 

```
use OneLogin\Saml2\Utils;

class MySamlController extends Controller {

    public function actions() {

        Utils::setProxyVars(true);
        ...
```

You can find a guide about this topic on the onelogin/php-saml repository 
https://github.com/onelogin/php-saml#url-guessing-methods

**Comment by ilbassa** [comment]
@motzy Thanks, you solved a big problem for us!

**Comment by seshendramln** [comment]
@motzy Thank you. It solved the issue. Hence, I am closing the request.
