### ISSUE TITLE
Class 'OneLogin_Saml2_Auth' not found

### ISSUE THREAD

**Issue by asminog** [asasmoyo/yii2-saml#8]
Get it in fresh installation

Suppose that because onelogin/php-saml "3.0.0" loaded as dependency

**Comment by asasmoyo** [comment]
`composer.json` states that `"onelogin/php-saml": ">=2.10.0"`, no wonder if it tries to install v3. It is better to have it with `~2.13.0`.

Can you submit a pr with this change and also update `composer.lock`? I don't have php environment at the moment.

**Comment by juliardi** [comment]
I've sent a pull request here #10

**Comment by asasmoyo** [comment]
@asminog let us know if you are still experiencing that
